_G = _G or (getfenv and getfenv(0)) or {}

LATEST_VERSION = "19.11"
RLC_STYLE = _G.RLC_Styles or {}
RLC_UI_MODERN = _G.RLC_UIModernization or {}

SEP = "\31"
SECONDS_PER_DAY = 86400
SECONDS_PER_HOUR = 3600
OUTDATED_VERSION_POPUP_COOLDOWN = 24 * SECONDS_PER_HOUR
GROUP_MIN_TIME = 300
GROUP_COOLDOWN = 900
GROUP_POINT_INTERVAL = 3600
GUILD_ROSTER_CACHE_DURATION = 30
SHOUTOUT_MAX_PER_DAY = 2
WORK_ORDER_LOGIN_ALERT_COOLDOWN = 24 * SECONDS_PER_HOUR
LBOARD_RESYNC_COOLDOWN = 30
LBOARD_RESPOND_COOLDOWN = 30
MYSTATS_RESPOND_COOLDOWN = 5
MAX_FUTURE_EPOCH_OFFSET = 7 * SECONDS_PER_DAY
SHOUT_SYNC_RESPOND_COOLDOWN = 30
DEFAULT_ACHIEVEMENT_POINTS = 10
FULL_WIPE_GUILD_MARKER = "RLCFW"
FULL_WIPE_GUILD_MARKER_PATTERN = "%[" .. FULL_WIPE_GUILD_MARKER .. ":(%d+)%]"
FULL_WIPE_GUILD_MARKER_STRIP_PATTERN = "%s*%[" .. FULL_WIPE_GUILD_MARKER .. ":%d+%]%s*"

GEAR_BROADCAST_THROTTLE = 10
GEAR_CAPTURE_CACHE_WINDOW = 5
GEAR_REQUEST_THROTTLE = 8
GEAR_EVENT_DEBOUNCE = 0.2
GUILD_BANK_REFRESH_DEBOUNCE = 0.2
